### ISSUE TITLE
1.0 checklist

### ISSUE THREAD

**Issue by CAD97** [rust-analyzer/text-size#24]
This is a meta issue tracking concerns that have been raised and should be addressed before publishing a 1.0 version. Once all of the checkboxes here are checked, we should be good for a 1.0 release.

- [x] Should `TextSize::of` use APIT or an explicit generic? (IOW, should `TextSize::of::<&str>(s)` be allowed? Using this form would allow deref coercion to kick in.)
  - [x] Related, should we provide a deref-coercion-like recursive impl for `TextSized`?
- [x] Should `TextSized` get a "uglier" name, as it is not meant to be used directly? (And `TextSized`/`TextSize` are _very_ close names.)
  - `LenTextSize::len_text_size` has been proposed.
- [x] `TextRange::empty(offset)` or `TextRange::empty()` (and thus `TextRange::empty() + offset` to get the offset behavior)?

<details><summary>API Guidelines</summary>

- **Naming** *(crate aligns with Rust naming conventions)*
  - [x] Casing conforms to RFC 430 ([C-CASE])
  - [x] Ad-hoc conversions follow `as_`, `to_`, `into_` conventions ([C-CONV])
  - [x] Getter names follow Rust convention ([C-GETTER])
  - [x] Methods on collections that produce iterators follow `iter`, `iter_mut`, `into_iter` ([C-ITER])
  - [x] Iterator type names match the methods that produce them ([C-ITER-TY])
  - [x] Feature names are free of placeholder words ([C-FEATURE])
  - [x] Names use a consistent word order ([C-WORD-ORDER])
- **Interoperability** *(crate interacts nicely with other library functionality)*
  - [x] Types eagerly implement common traits ([C-COMMON-TRAITS])
    - `Copy`, `Clone`, `Eq`, `PartialEq`, `Ord`, `PartialOrd`, `Hash`, `Debug`,
      `Display`, `Default`
  - [x] Conversions use the standard traits `From`, `AsRef`, `AsMut` ([C-CONV-TRAITS])
  - [x] Collections implement `FromIterator` and `Extend` ([C-COLLECT])
  - [x] Data structures implement Serde's `Serialize`, `Deserialize` ([C-SERDE])
  - [x] Types are `Send` and `Sync` where possible ([C-SEND-SYNC])
  - [x] Error types are meaningful and well-behaved ([C-GOOD-ERR])
  - [x] Binary number types provide `Hex`, `Octal`, `Binary` formatting ([C-NUM-FMT])
  - [x] Generic reader/writer functions take `R: Read` and `W: Write` by value ([C-RW-VALUE])
- **Macros** *(crate presents well-behaved macros)*
  - [x] Input syntax is evocative of the output ([C-EVOCATIVE])
  - [x] Macros compose well with attributes ([C-MACRO-ATTR])
  - [x] Item macros work anywhere that items are allowed ([C-ANYWHERE])
  - [x] Item macros support visibility specifiers ([C-MACRO-VIS])
  - [x] Type fragments are flexible ([C-MACRO-TY])
- **Documentation** *(crate is abundantly documented)*
  - [ ] Crate level docs are thorough and include examples ([C-CRATE-DOC])
  - [x] All items have a rustdoc example ([C-EXAMPLE])
  - [x] Examples use `?`, not `try!`, not `unwrap` ([C-QUESTION-MARK])
  - [x] Function docs include error, panic, and safety considerations ([C-FAILURE])
  - [x] Prose contains hyperlinks to relevant things ([C-LINK])
  - [ ] Cargo.toml includes all common metadata ([C-METADATA])
    - authors, description, license, homepage, documentation, repository,
      readme, keywords, categories
  - [x] Crate sets html_root_url attribute "https://docs.rs/CRATE/X.Y.Z" ([C-HTML-ROOT])
  - [x] Release notes document all significant changes ([C-RELNOTES])
  - [x] Rustdoc does not show unhelpful implementation details ([C-HIDDEN])
- **Predictability** *(crate enables legible code that acts how it looks)*
  - [x] Smart pointers do not add inherent methods ([C-SMART-PTR])
  - [x] Conversions live on the most specific type involved ([C-CONV-SPECIFIC])
  - [x] Functions with a clear receiver are methods ([C-METHOD])
  - [x] Functions do not take out-parameters ([C-NO-OUT])
  - [x] Operator overloads are unsurprising ([C-OVERLOAD])
  - [x] Only smart pointers implement `Deref` and `DerefMut` ([C-DEREF])
  - [x] Constructors are static, inherent methods ([C-CTOR])
- **Flexibility** *(crate supports diverse real-world use cases)*
  - [x] Functions expose intermediate results to avoid duplicate work ([C-INTERMEDIATE])
  - [x] Caller decides where to copy and place data ([C-CALLER-CONTROL])
  - [x] Functions minimize assumptions about parameters by using generics ([C-GENERIC])
  - [x] Traits are object-safe if they may be useful as a trait object ([C-OBJECT])
- **Type safety** *(crate leverages the type system effectively)*
  - [x] Newtypes provide static distinctions ([C-NEWTYPE])
  - [x] Arguments convey meaning through types, not `bool` or `Option` ([C-CUSTOM-TYPE])
  - [x] Types for a set of flags are `bitflags`, not enums ([C-BITFLAG])
  - [x] Builders enable construction of complex values ([C-BUILDER])
- **Dependability** *(crate is unlikely to do the wrong thing)*
  - [x] Functions validate their arguments ([C-VALIDATE])
  - [x] Destructors never fail ([C-DTOR-FAIL])
  - [x] Destructors that may block have alternatives ([C-DTOR-BLOCK])
- **Debuggability** *(crate is conducive to easy debugging)*
  - [x] All public types implement `Debug` ([C-DEBUG])
  - [x] `Debug` representation is never empty ([C-DEBUG-NONEMPTY])
- **Future proofing** *(crate is free to improve without breaking users' code)*
  - [x] Sealed traits protect against downstream implementations ([C-SEALED])
  - [x] Structs have private fields ([C-STRUCT-PRIVATE])
  - [x] Newtypes encapsulate implementation details ([C-NEWTYPE-HIDE])
  - [x] Data structures do not duplicate derived trait bounds ([C-STRUCT-BOUNDS])
- **Necessities** *(to whom they matter, they really matter)*
  - [x] Public dependencies of a stable crate are stable ([C-STABLE])
  - [x] Crate and its dependencies have a permissive license ([C-PERMISSIVE])

[C-CASE]: https://rust-lang.github.io/api-guidelines/naming.html#c-case
[C-CONV]: https://rust-lang.github.io/api-guidelines/naming.html#c-conv
[C-GETTER]: https://rust-lang.github.io/api-guidelines/naming.html#c-getter
[C-ITER]: https://rust-lang.github.io/api-guidelines/naming.html#c-iter
[C-ITER-TY]: https://rust-lang.github.io/api-guidelines/naming.html#c-iter-ty
[C-FEATURE]: https://rust-lang.github.io/api-guidelines/naming.html#c-feature
[C-WORD-ORDER]: https://rust-lang.github.io/api-guidelines/naming.html#c-word-order

[C-COMMON-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits
[C-CONV-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-conv-traits
[C-COLLECT]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-collect
[C-SERDE]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-serde
[C-SEND-SYNC]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-send-sync
[C-GOOD-ERR]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-good-err
[C-NUM-FMT]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-num-fmt
[C-RW-VALUE]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-rw-value

[C-EVOCATIVE]: https://rust-lang.github.io/api-guidelines/macros.html#c-evocative
[C-MACRO-ATTR]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-attr
[C-ANYWHERE]: https://rust-lang.github.io/api-guidelines/macros.html#c-anywhere
[C-MACRO-VIS]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-vis
[C-MACRO-TY]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-ty

[C-CRATE-DOC]: https://rust-lang.github.io/api-guidelines/documentation.html#c-crate-doc
[C-EXAMPLE]: https://rust-lang.github.io/api-guidelines/documentation.html#c-example
[C-QUESTION-MARK]: https://rust-lang.github.io/api-guidelines/documentation.html#c-question-mark
[C-FAILURE]: https://rust-lang.github.io/api-guidelines/documentation.html#c-failure
[C-LINK]: https://rust-lang.github.io/api-guidelines/documentation.html#c-link
[C-METADATA]: https://rust-lang.github.io/api-guidelines/documentation.html#c-metadata
[C-HTML-ROOT]: https://rust-lang.github.io/api-guidelines/documentation.html#c-html-root
[C-RELNOTES]: https://rust-lang.github.io/api-guidelines/documentation.html#c-relnotes
[C-HIDDEN]: https://rust-lang.github.io/api-guidelines/documentation.html#c-hidden

[C-SMART-PTR]: https://rust-lang.github.io/api-guidelines/predictability.html#c-smart-ptr
[C-CONV-SPECIFIC]: https://rust-lang.github.io/api-guidelines/predictability.html#c-conv-specific
[C-METHOD]: https://rust-lang.github.io/api-guidelines/predictability.html#c-method
[C-NO-OUT]: https://rust-lang.github.io/api-guidelines/predictability.html#c-no-out
[C-OVERLOAD]: https://rust-lang.github.io/api-guidelines/predictability.html#c-overload
[C-DEREF]: https://rust-lang.github.io/api-guidelines/predictability.html#c-deref
[C-CTOR]: https://rust-lang.github.io/api-guidelines/predictability.html#c-ctor

[C-INTERMEDIATE]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-intermediate
[C-CALLER-CONTROL]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-caller-control
[C-GENERIC]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-generic
[C-OBJECT]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-object

[C-NEWTYPE]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-newtype
[C-CUSTOM-TYPE]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-custom-type
[C-BITFLAG]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-bitflag
[C-BUILDER]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-builder

[C-VALIDATE]: https://rust-lang.github.io/api-guidelines/dependability.html#c-validate
[C-DTOR-FAIL]: https://rust-lang.github.io/api-guidelines/dependability.html#c-dtor-fail
[C-DTOR-BLOCK]: https://rust-lang.github.io/api-guidelines/dependability.html#c-dtor-block

[C-DEBUG]: https://rust-lang.github.io/api-guidelines/debuggability.html#c-debug
[C-DEBUG-NONEMPTY]: https://rust-lang.github.io/api-guidelines/debuggability.html#c-debug-nonempty

[C-SEALED]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-sealed
[C-STRUCT-PRIVATE]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-struct-private
[C-NEWTYPE-HIDE]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-newtype-hide
[C-STRUCT-BOUNDS]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-struct-bounds

[C-STABLE]: https://rust-lang.github.io/api-guidelines/necessities.html#c-stable
[C-PERMISSIVE]: https://rust-lang.github.io/api-guidelines/necessities.html#c-permissive

</details>

**Comment by matklad** [comment]
I'd also try to think of a better name for `offset_len`. In https://github.com/CAD97/rowan/pull/3/files, up_to is used only as a part of + offset pattern....

```
TextRange::new(start, end);
TextRange::with_len(start, end);
TextRange::offset_len(start, end);
```

And maybe to re-thing the `fn TextRange` hack. `TextRange::new` would be a boring equivalent

**Comment by matklad** [comment]
Argh, its excruciating, C# uses `::new(start, len)`, and they get to use `::from_bounds` for the other ctor. But I do believe that `from_bounds` should be the canonical ctor (it's twice as frequent as `offset_len` in rust-analyzer).

**Comment by CAD97** [comment]
The PRs I just opened address all of the remaining specific concerns.

After that is just making sure that we're happy with our state against the API guidelines, and then we're good to release. (Though it may be still worth it to release as 0.99, so if we find anything while updating rowan and rust-analyzer for real, we still have the flexibility to make more changes.)

**Comment by matklad** [comment]
I do feel that we should do `0.99`, update rowan and ra, and then do 1.0

**Comment by CAD97** [comment]
For visibility, the API guidelines I haven't checked off yet:

- **Documentation** *(crate is abundantly documented)*
  - [ ] Crate level docs are thorough and include examples ([C-CRATE-DOC])
  - [ ] All items have a rustdoc example ([C-EXAMPLE])
  - [ ] Function docs include error, panic, and safety considerations ([C-FAILURE])
  - [ ] Prose contains hyperlinks to relevant things ([C-LINK])
  - [ ] Cargo.toml includes all common metadata ([C-METADATA])
    - authors, description, license, homepage, documentation, repository,
      readme, keywords, categories
  - [ ] Crate sets html_root_url attribute "https://docs.rs/CRATE/X.Y.Z" ([C-HTML-ROOT])
  - [ ] Release notes document all significant changes ([C-RELNOTES])
- **Future proofing** *(crate is free to improve without breaking users' code)*
  - [ ] Sealed traits protect against downstream implementations ([C-SEALED])

I think:

- We could use some crate-level docs at least, maybe explaining the benefit of using `TextSize`/`TextRange` over `usize`/`ops::Range<usize>`?
- Small examples are hard.
- Do we need to add more error/panic/safety considerations? We do have some panicking cases without explicit `# Panics` docs sections, such as `<&str as LenTextSize>::len_text_size` (and thus `TextSize::of`).
- I think I've made sure relevant things are always linked?
- We don't have a homepage, so that's out. Readme, keywords, and categories should be set.
- [C-HTML-ROOT is obsolete](https://github.com/rust-lang/api-guidelines/issues/78#issuecomment-604159242)
- We should probably [keep a changelog](https://keepachangelog.com/en/1.0.0/), even if it only starts with version 0.99.
- `LenTextSized` _might_ want to be sealed, we just need to make that decision explicitly (again?).

And the final concern: mark text-unit as deprecated and point users at text-size.


[C-CASE]: https://rust-lang.github.io/api-guidelines/naming.html#c-case
[C-CONV]: https://rust-lang.github.io/api-guidelines/naming.html#c-conv
[C-GETTER]: https://rust-lang.github.io/api-guidelines/naming.html#c-getter
[C-ITER]: https://rust-lang.github.io/api-guidelines/naming.html#c-iter
[C-ITER-TY]: https://rust-lang.github.io/api-guidelines/naming.html#c-iter-ty
[C-FEATURE]: https://rust-lang.github.io/api-guidelines/naming.html#c-feature
[C-WORD-ORDER]: https://rust-lang.github.io/api-guidelines/naming.html#c-word-order

[C-COMMON-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits
[C-CONV-TRAITS]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-conv-traits
[C-COLLECT]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-collect
[C-SERDE]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-serde
[C-SEND-SYNC]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-send-sync
[C-GOOD-ERR]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-good-err
[C-NUM-FMT]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-num-fmt
[C-RW-VALUE]: https://rust-lang.github.io/api-guidelines/interoperability.html#c-rw-value

[C-EVOCATIVE]: https://rust-lang.github.io/api-guidelines/macros.html#c-evocative
[C-MACRO-ATTR]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-attr
[C-ANYWHERE]: https://rust-lang.github.io/api-guidelines/macros.html#c-anywhere
[C-MACRO-VIS]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-vis
[C-MACRO-TY]: https://rust-lang.github.io/api-guidelines/macros.html#c-macro-ty

[C-CRATE-DOC]: https://rust-lang.github.io/api-guidelines/documentation.html#c-crate-doc
[C-EXAMPLE]: https://rust-lang.github.io/api-guidelines/documentation.html#c-example
[C-QUESTION-MARK]: https://rust-lang.github.io/api-guidelines/documentation.html#c-question-mark
[C-FAILURE]: https://rust-lang.github.io/api-guidelines/documentation.html#c-failure
[C-LINK]: https://rust-lang.github.io/api-guidelines/documentation.html#c-link
[C-METADATA]: https://rust-lang.github.io/api-guidelines/documentation.html#c-metadata
[C-HTML-ROOT]: https://rust-lang.github.io/api-guidelines/documentation.html#c-html-root
[C-RELNOTES]: https://rust-lang.github.io/api-guidelines/documentation.html#c-relnotes
[C-HIDDEN]: https://rust-lang.github.io/api-guidelines/documentation.html#c-hidden

[C-SMART-PTR]: https://rust-lang.github.io/api-guidelines/predictability.html#c-smart-ptr
[C-CONV-SPECIFIC]: https://rust-lang.github.io/api-guidelines/predictability.html#c-conv-specific
[C-METHOD]: https://rust-lang.github.io/api-guidelines/predictability.html#c-method
[C-NO-OUT]: https://rust-lang.github.io/api-guidelines/predictability.html#c-no-out
[C-OVERLOAD]: https://rust-lang.github.io/api-guidelines/predictability.html#c-overload
[C-DEREF]: https://rust-lang.github.io/api-guidelines/predictability.html#c-deref
[C-CTOR]: https://rust-lang.github.io/api-guidelines/predictability.html#c-ctor

[C-INTERMEDIATE]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-intermediate
[C-CALLER-CONTROL]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-caller-control
[C-GENERIC]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-generic
[C-OBJECT]: https://rust-lang.github.io/api-guidelines/flexibility.html#c-object

[C-NEWTYPE]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-newtype
[C-CUSTOM-TYPE]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-custom-type
[C-BITFLAG]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-bitflag
[C-BUILDER]: https://rust-lang.github.io/api-guidelines/type-safety.html#c-builder

[C-VALIDATE]: https://rust-lang.github.io/api-guidelines/dependability.html#c-validate
[C-DTOR-FAIL]: https://rust-lang.github.io/api-guidelines/dependability.html#c-dtor-fail
[C-DTOR-BLOCK]: https://rust-lang.github.io/api-guidelines/dependability.html#c-dtor-block

[C-DEBUG]: https://rust-lang.github.io/api-guidelines/debuggability.html#c-debug
[C-DEBUG-NONEMPTY]: https://rust-lang.github.io/api-guidelines/debuggability.html#c-debug-nonempty

[C-SEALED]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-sealed
[C-STRUCT-PRIVATE]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-struct-private
[C-NEWTYPE-HIDE]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-newtype-hide
[C-STRUCT-BOUNDS]: https://rust-lang.github.io/api-guidelines/future-proofing.html#c-struct-bounds

[C-STABLE]: https://rust-lang.github.io/api-guidelines/necessities.html#c-stable
[C-PERMISSIVE]: https://rust-lang.github.io/api-guidelines/necessities.html#c-permissive

**Comment by matklad** [comment]
TBH, I feel like only the changelog would add significant value here.  It's not like `TextSize` will become a super foundational crate which requires rigorous approach to maintainence.

But it probably makes sense to add a top-level doc along the lines of "unless you plan to pervasively use and store `TextRange`s, prefer to forumalte your crate's API in terms of ranges of `usize`". I.e, I worry more that the crate will be missued. I've recently seen a blog post about lexers, which used text-size, which I think is a missuse -- a generic lexer has noting to gain (and generality and interop to loose) from switching to text-size.

**Comment by matklad** [comment]
ping @CAD97 what are our further action items here? I think just migrating rowan and rust-analyzer to 0.99? Would be willing to try this out?

**Comment by matklad** [comment]
gentle re-ping @CAD97 (:

**Comment by CAD97** [comment]
Concrete things I'd like to see:

- A changelog somewhere. This should be the proper home of the `text_unit => text-size` translation tables, rather than directly in the docs. (Also, I forgot to change the translation table for the `from_len => at` rename.)
- Crate level docs (and readme) discuss when to (not) use the crate.
- Missing Cargo metadata should be added (readme, keywords, categories).
- Redo the rowan and r-a ports as a final sanity check. I'm doing this now.

**Comment by matklad** [comment]
>This should be the proper home of the text_unit => text-size translation tables, rather than directly in the docs

I believe the cumulative value of the transition table in the docs over the lifetime will be negative, so yeah, we should put it into a changelog (or just remove altogether, I think it's intuitive enough)

**Comment by CAD97** [comment]
rowan patch: <https://github.com/CAD97/rowan/pull/3>
ra-patch: <https://github.com/CAD97/rust-analyzer/pull/1>

Notes, again:

- We might want a smol-str update that does `impl TextLen for &'_ SmolStr`.
- _maybe_ provide `usize as From<&TextSize>` as well?
- `cargo insta review` is a blessing for widespread trivial changes like changing the formatting of `TextRange` which changes the format of literally every snapshot test in r-a; can we have that for the remaining tests yesterday so I don't have to go and fix every one manually please 
![image](https://user-images.githubusercontent.com/5992217/78731953-3e01d800-790f-11ea-9649-641e966e5d54.png)
![image](https://user-images.githubusercontent.com/5992217/78731964-465a1300-790f-11ea-8f6e-ebceb5c2faf1.png)
this is after getting as far as I can with `INSTA_UPDATE=always cargo test --workspace`
- I did fix every test with search&replace and I should have put it in a separate commit but I really don't want to redo it
- because it was painful and not even perfectly accurate the first time and had to be cleaned up manually afterwards
- we need to get directory-sniffing tests into `insta` proper so `cargo insta review` works for them

**Comment by CAD97** [comment]
Adding glob based parameterized tests into insta ended up being easier than I initially expected and ran into the first time: https://github.com/mitsuhiko/insta/pull/109

**Comment by matklad** [comment]
>can we have that for the remaining tests yesterday

I am not sure what are you trying to say here, but, if you don't feel like updating the tests, I certainly can do this myself!

**Comment by CAD97** [comment]
Mainly that there are a number of tests (read: every single `.rast` test) that are not updated by doing `cargo insta test --accept` (or any of the other ways to bless insta tests) and if there's a way to bless them, it's not clear to me. I did update all the `.rast` tests with a regex, but it broke and didn't work in some cases that I had to fix manually.

It'd be awesome to get the `.rast` tests using insta as well so `cargo insta review` just works, and to that end I've opened a PR against insta adding the needed glob-based test discovery.

It would have saved me a lot of effort had the tests been using insta already. (Now if you do want to help make the patch better, separating the actual code changes from the test updates really should be done.)

I'm happy publishing 0.99 once we have moved the text_unit translation tables to a changelog and added "when to use this" documentation. (Both of which I'd rather you write tbh :stuck_out_tounge: )

**Comment by matklad** [comment]
>and if there's a way to bless them, it's not clear to me.

Aha, there's indeed a way: https://github.com/rust-analyzer/rust-analyzer/blob/779555c1beac90f633c01a773558c4007c99c97f/crates/test_utils/src/lib.rs#L398

**Comment by matklad** [comment]
Published 0.99

**Comment by matklad** [comment]
cc @BurntSushi, this is tangentially related to your work in text search area:

We publishing the 1.0 crate with "vocabulary" types for text offsets (`struct TextSize(u32)`)  and text ranges (`struct TextRange(u32, u32)`). These types might be useful for cases like IDEs and text editors, but are explicitly **not** intended for general low-level utilites like regex engines or lexers (this is [called out](https://github.com/rust-analyzer/text-size/blob/d7ef23ad453337a2e79d44440a22d28efe7bb4d5/src/lib.rs#L9-L15) in the docs).

No action is expected, this is just to let you know that the thing exists :)

**Comment by matklad** [comment]
@CAD97 is some work here blocked on me? Are we ready to basically just swithc rust-analyzer to this?

**Comment by CAD97** [comment]
Yeah, the remaining steps are to update r-a to the version of rowan using 0.99, then assuming everything works, publish 1.0, update rowan to use it, update r-a to use that version of rowan.

**Comment by matklad** [comment]
Good, I'll do this now

**Comment by matklad** [comment]
1.0 is published!
